### ISSUE TITLE
Inquiry about Citation for Your Project

### ISSUE THREAD

**Issue by Alienworm** [K-Kyungho/PET#1]
Hello!
I am a user who is highly interested in the PET you published on GitHub. This project has been of great assistance to my research. I would like to express my sincere gratitude to you first.
I am currently writing a related paper and, in order to follow academic norms and give appropriate citations to your work, I hope to receive your formal Citation guidance for this project.
Would it be convenient for you to provide me with an appropriate Citation format or related instructions? Thank you very much for taking the time to assist me.
Looking forward to your reply. Wish you all the best!

**Comment by K-Kyungho** [comment]
Hi @Alienworm !

Thank you for your interest in my research. I'm glad to hear that my work has been helpful to your research. The formal citation guidance for our paper is provided below.

@inproceedings{kim2024towards,
  title={Towards Better Utilization of Multiple Views for Bundle Recommendation},
  author={Kim, Kyungho and Kim, Sunwoo and Lee, Geon and Shin, Kijung},
  booktitle={CIKM},
  year={2024}
}

Best regards,

Kyungho

**Comment by Alienworm** [comment]
> Hi @Alienworm !
> 
> Thank you for your interest in my research. I'm glad to hear that my work has been helpful to your research. The formal citation guidance for our paper is provided below.
> 
> @inproceedings{kim2024towards, title={Towards Better Utilization of Multiple Views for Bundle Recommendation}, author={Kim, Kyungho and Kim, Sunwoo and Lee, Geon and Shin, Kijung}, booktitle={CIKM}, year={2024} }
> 
> Best regards,
> 
> Kyungho

Thanks a lot.
