### ISSUE TITLE
Request for Article Abstract

### ISSUE THREAD

**Issue by Alienworm** [K-Kyungho/PET#2]
Hello!
I was wondering if it would be possible for you to provide the abstract section of your article? This would greatly help me in understanding the key points and significance of your work without having to go through the entire piece immediately.
Looking forward to your reply. Wish you all the best!

**Comment by K-Kyungho** [comment]
Hello! 

Thank you for your interest in my research. The abstract of our paper is below. 

_Bundle recommender systems aim to recommend suitable collections (i.e., bundles) of items to each user, meeting their diverse
needs with all-in-one convenience. Typically, they utilize three distinct types of information: user-bundle purchase interactions (U-B view), user-item purchase interactions (U-I view), and bundle-item affiliations (B-I view). Our focus is on better integrating these three perspectives (i.e., views) to deliver more accurate bundle recommendations. Our examination of different role (main or sub-views) combinations of the views reveals two key observations: (1) the best combination varies across target users (i.e., who receive recommendations), and (2) the U-I view is relatively weak as the main role. Driven by these observations, we propose PET, which synergizes the three views through (1) personalized view weighting, (2) U-I view enhancement, and (3) two-pronged contrastive learning. Our extensive experiments demonstrate that PET significantly outperforms existing methods in all popular benchmark datasets._

Best regards,

Kyungho

**Comment by Alienworm** [comment]
Thanks a lot.
