### ISSUE TITLE
Request for Dataset Statistics 

### ISSUE THREAD

**Issue by juyeonnn** [K-Kyungho/PET#5]
Thanks for sharing your research. Could you provide details about the dataset statistics? This information would help with understanding and reproducing the work. Thanks!

**Comment by K-Kyungho** [comment]
Thanks for your comments. 
![image](https://github.com/user-attachments/assets/b28d88a5-7d3d-4c37-a1e2-508bac5e29b6)
This is the statistics of datasets. Please let me know if you have further questions on data statistics!
